# Generated by Django 3.1.13 on 2022-04-05 19:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0007_device_secrets_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnusedPorts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_output', models.DateTimeField()),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.interface')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
