# Generated by Django 3.1.13 on 2022-04-10 18:52

from django.db import migrations, models
import django.db.models.deletion
import nautobot.dcim.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_porthistory_plugin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MAConPorts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('mac', nautobot.dcim.fields.MACAddressCharField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.device')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcim.interface')),
                ('ipaddress', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.ipaddress')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.vlan')),
            ],
            options={
                'verbose_name_plural': 'MAC and IP on switches ports',
            },
        ),
    ]
